import type { ThemeDefinition } from "../types";

/** Contrast — accessibility-focused, WCAG AAA text contrast. */
export const contrast: ThemeDefinition = {
  id: "contrast",
  name: "Contrast",
  mode: "high-contrast",
  description: "High-contrast theme, WCAG AAA. Black on white surfaces with bold text.",
  builtIn: true,
  tokens: {
    surfaceApp: "#000000",
    surfacePanel: "#0A0A0A",
    surfaceRaised: "#141414",
    surfaceSunken: "#000000",
    surfaceHover: "#1E1E1E",
    surfaceActive: "#282828",
    borderSubtle: "#2E2E2E",
    borderStrong: "#444444",
    borderInput: "#4A4A4A",
    textPrimary: "#FFFFFF",
    textSecondary: "#E0E0E0",
    textMuted: "#B5B5B5",
    textDisabled: "#808080",
    accent: "#FFD23F",
    accentHover: "#FFDB5C",
    accentActive: "#FFE479",
    accentContrast: "#000000",
    statusSuccess: "#7DD87D",
    statusWarning: "#FFC04D",
    statusError: "#E87878",
    statusInfo: "#7DB7FF",
    priorityUrgent: "#E87878",
    priorityHigh: "#FFA040",
    priorityNormal: "#FFC04D",
    priorityLow: "#7DB7FF",
    prioritySuggestion: "#7DD87D",
    monaco: {
      bg: "#000000",
      fg: "#FFFFFF",
      gutter: "#2E2E2E",
      gutterActive: "#FFFFFF",
      lineHighlight: "#1E1E1E",
      selection: "rgba(255, 210, 63, 0.30)",
      cursor: "#FFD23F",
      whitespace: "#444444",
      syntax: {
        comment: "#B5B5B5",
        string: "#7DD87D",
        number: "#FFC04D",
        keyword: "#7DB7FF",
        function: "#FFD23F",
        type: "#FF9DFF",
        macro: "#FFC04D",
        attribute: "#7DB7FF",
        variable: "#FFFFFF",
        constant: "#FFC04D",
        operator: "#E0E0E0",
        punctuation: "#FFFFFF",
        tag: "#7DB7FF",
        attributeName: "#FFD23F",
        attributeValue: "#7DD87D",
        property: "#FFD23F",
      },
    },
    terminal: {
      background: "#000000",
      foreground: "#FFFFFF",
      cursor: "#FFD23F",
      selection: "rgba(255, 210, 63, 0.30)",
      black: "#000000",
      red: "#E87878",
      green: "#7DD87D",
      yellow: "#FFC04D",
      blue: "#7DB7FF",
      magenta: "#FF9DFF",
      cyan: "#7DFFFF",
      white: "#FFFFFF",
      brightBlack: "#808080",
      brightRed: "#F0A0A0",
      brightGreen: "#A0EBA0",
      brightYellow: "#FFD680",
      brightBlue: "#A0C8FF",
      brightMagenta: "#FFBFFF",
      brightCyan: "#A0FFFF",
      brightWhite: "#FFFFFF",
    },
  },
};
