import type { ThemeDefinition } from "../types";

/**
 * Midnight — default dark theme.
 * Near-black neutrals with a single muted teal accent.
 * Inspired by Linear / Zed dark surfaces.
 */
export const midnight: ThemeDefinition = {
  id: "midnight",
  name: "Midnight",
  mode: "dark",
  description: "Near-black neutrals with a muted teal accent. The default dark theme.",
  builtIn: true,
  defaultForMode: true,
  tokens: {
    surfaceApp: "#0D0E11",
    surfacePanel: "#131418",
    surfaceRaised: "#1A1B20",
    surfaceSunken: "#0A0B0E",
    surfaceHover: "#202227",
    surfaceActive: "#26282E",
    borderSubtle: "#1F2024",
    borderStrong: "#2A2C31",
    borderInput: "#2D2F35",
    textPrimary: "#E6E7EA",
    textSecondary: "#A8AAB0",
    textMuted: "#6E7178",
    textDisabled: "#4A4D54",
    accent: "#4F8C8C",
    accentHover: "#5B9D9D",
    accentActive: "#69AEAE",
    accentContrast: "#FFFFFF",
    statusSuccess: "#6FA885",
    statusWarning: "#C9A66B",
    statusError: "#B07A8A",
    statusInfo: "#7B96B3",
    priorityUrgent: "#B07A8A",
    priorityHigh: "#D29464",
    priorityNormal: "#C9A66B",
    priorityLow: "#7B96B3",
    prioritySuggestion: "#6FA885",
    monaco: {
      bg: "#0D0E11",
      fg: "#D8DADE",
      gutter: "#2A2C31",
      gutterActive: "#4A4D54",
      lineHighlight: "#1A1B20",
      selection: "rgba(79, 140, 140, 0.24)",
      cursor: "#4F8C8C",
      whitespace: "#2A2C31",
      syntax: {
        comment: "#6E7178",
        string: "#9DB48A",
        number: "#C9A66B",
        keyword: "#7B96B3",
        function: "#8FB3B3",
        type: "#A88FB3",
        macro: "#C9A66B",
        attribute: "#7B96B3",
        variable: "#D8DADE",
        constant: "#C9A66B",
        operator: "#A8AAB0",
        punctuation: "#8E9098",
        tag: "#7B96B3",
        attributeName: "#8FB3B3",
        attributeValue: "#9DB48A",
        property: "#8FB3B3",
      },
    },
    terminal: {
      background: "#0D0E11",
      foreground: "#D8DADE",
      cursor: "#4F8C8C",
      selection: "rgba(79, 140, 140, 0.24)",
      black: "#0D0E11",
      red: "#B07A8A",
      green: "#6FA885",
      yellow: "#C9A66B",
      blue: "#7B96B3",
      magenta: "#A88FB3",
      cyan: "#4F8C8C",
      white: "#D8DADE",
      brightBlack: "#4A4D54",
      brightRed: "#C89AAA",
      brightGreen: "#88BC9F",
      brightYellow: "#D9B97D",
      brightBlue: "#94AEC5",
      brightMagenta: "#BCA3C7",
      brightCyan: "#69AEAE",
      brightWhite: "#FFFFFF",
    },
  },
};
