/**
 * Initial sample project for the Soroban.Build IDE.
 * A minimal hello-world Soroban contract workspace.
 */

export interface FileNode {
  type: "file";
  name: string;
  path: string;
  content: string;
  language: string;
  gitStatus?: "modified" | "added" | "untracked" | null;
}

export interface FolderNode {
  type: "folder";
  name: string;
  path: string;
  children: TreeNode[];
  expanded?: boolean;
}

export type TreeNode = FileNode | FolderNode;

export const SAMPLE_CONTRACT_RUST = `#![no_std]

use soroban_sdk::{contract, contractimpl, vec, Env, String, Vec};

/// A simple Hello World contract.
/// Stores the last greeting and lets you read it back.
#[contract]
pub struct HelloWorld;

#[contractimpl]
impl HelloWorld {
    /// Initialize the contract with a default greeting.
    pub fn __constructor(env: Env) {
        let default_greeting = String::from_str(&env, "Hello");
        env.storage().instance().set(&GREETING_KEY, &default_greeting);
    }

    /// Set a new greeting. Returns the new greeting.
    pub fn set_greeting(env: Env, greeting: String) -> String {
        env.storage().instance().set(&GREETING_KEY, &greeting);
        greeting
    }

    /// Read the current greeting.
    pub fn get_greeting(env: Env) -> String {
        env.storage()
            .instance()
            .get(&GREETING_KEY)
            .unwrap_or_else(|| String::from_str(&env, "Hello"))
    }

    /// Returns a personalized greeting addressed to \`name\`.
    pub fn greet(env: Env, name: String) -> String {
        let greeting = Self::get_greeting(env.clone());
        if name.is_empty() {
            return greeting;
        }
        let mut parts: Vec<String> = vec![
            &env,
            greeting,
            String::from_str(&env, ", "),
            name,
            String::from_str(&env, "!"),
        ];
        parts.concat(&env)
    }
}

const GREETING_KEY: &str = "Greeting";
`;

export const SAMPLE_CARGO_TOML = `[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "22.0.0"

[dev_dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
`;

export const SAMPLE_README = `# Hello World

A minimal Soroban smart contract demonstrating:

- Contract definition with \`#[contract]\` and \`#[contractimpl]\`
- Instance storage via \`env.storage().instance()\`
- String manipulation with \`soroban_sdk::String\`
- Constructor (\`__constructor\`)
- Unit tests with \`soroban_sdk::testutils\`

## Build

\`\`\`sh
soroban contract build
\`\`\`

## Test

\`\`\`sh
cargo test
\`\`\`

## Deploy

\`\`\`sh
soroban contract deploy \\
  --wasm target/wasm32v1-none/release/hello_world.wasm \\
  --source-account <your-key> \\
  --network testnet
\`\`\`
`;

export const SAMPLE_GITIGNORE = `# Rust
/target
**/*.rs.bk

# Soroban
*.wasm
.soroban/

# Editor
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Env
.env
.env.local
`;

export const SAMPLE_UI_APP = `import { useEffect, useState } from "react";
import { deploy, invoke } from "@openzeppelin/adapter-stellar";

/**
 * UI for the Hello World contract.
 * Auto-generated by Soroban.Build from the contract spec.
 */
export default function HelloWorldUI({ contractId }: { contractId: string }) {
  const [greeting, setGreeting] = useState("");
  const [name, setName] = useState("");
  const [output, setOutput] = useState("");

  useEffect(() => {
    invoke(contractId, "get_greeting").then(setGreeting).catch(console.error);
  }, [contractId]);

  async function handleGreet() {
    const result = await invoke(contractId, "greet", [name]);
    setOutput(result);
  }

  return (
    <main>
      <h1>Hello World</h1>
      <p>Current greeting: {greeting}</p>
      <input value={name} onChange={(e) => setName(e.target.value)} />
      <button onClick={handleGreet}>Greet</button>
      {output && <p>Result: {output}</p>}
    </main>
  );
}
`;

export function getInitialFileTree(): TreeNode[] {
  return [
    {
      type: "folder",
      name: "src",
      path: "src",
      expanded: true,
      children: [
        {
          type: "file",
          name: "lib.rs",
          path: "src/lib.rs",
          language: "rust",
          content: SAMPLE_CONTRACT_RUST,
          gitStatus: null,
        },
        {
          type: "file",
          name: "test.rs",
          path: "src/test.rs",
          language: "rust",
          content:
            "#[cfg(test)]\nmod test {\n    use super::*;\n    use soroban_sdk::testutils::Address;\n\n    #[test]\n    fn test_default_greeting() {\n        // TODO\n    }\n}\n",
          gitStatus: "untracked",
        },
      ],
    },
    {
      type: "folder",
      name: "ui",
      path: "ui",
      expanded: false,
      children: [
        {
          type: "file",
          name: "App.tsx",
          path: "ui/App.tsx",
          language: "typescript",
          content: SAMPLE_UI_APP,
          gitStatus: null,
        },
      ],
    },
    {
      type: "file",
      name: "Cargo.toml",
      path: "Cargo.toml",
      language: "toml",
      content: SAMPLE_CARGO_TOML,
      gitStatus: null,
    },
    {
      type: "file",
      name: "README.md",
      path: "README.md",
      language: "markdown",
      content: SAMPLE_README,
      gitStatus: null,
    },
    {
      type: "file",
      name: ".gitignore",
      path: ".gitignore",
      language: "plaintext",
      content: SAMPLE_GITIGNORE,
      gitStatus: null,
    },
  ];
}

export function findFile(tree: TreeNode[], path: string): FileNode | null {
  for (const node of tree) {
    if (node.type === "file" && node.path === path) return node;
    if (node.type === "folder") {
      const found = findFile(node.children, path);
      if (found) return found;
    }
  }
  return null;
}

export function flattenFiles(tree: TreeNode[]): FileNode[] {
  const result: FileNode[] = [];
  function walk(nodes: TreeNode[]) {
    for (const node of nodes) {
      if (node.type === "file") result.push(node);
      else walk(node.children);
    }
  }
  walk(tree);
  return result;
}
