#!/bin/bash
# scripts/setup-stellar-cli.sh
#
# Installs and configures the Stellar CLI with shell autocompletion.
# Follows the official setup guide:
# https://developers.stellar.org/docs/build/smart-contracts/getting-started/setup
#
# What this script does:
#   1. Installs the Rust toolchain (rustup + rustc + cargo) if missing
#   2. Adds the wasm32v1-none target (required for Soroban contracts)
#   3. Installs rust-analyzer (for IDE LSP autocomplete)
#   4. Installs stellar-cli (pre-built binary from GitHub releases)
#   5. Generates + installs shell completion for bash, zsh, and fish
#   6. Configures ~/.bashrc with PATH + completion sourcing + aliases
#
# Usage: bash scripts/setup-stellar-cli.sh
#
# After running, restart your shell (or `source ~/.bashrc`) to activate
# tab completion. Try it: type `stellar <TAB>` or `stellar contract <TAB>`.

set -e

export HOME="${HOME:-/home/z}"
STELLAR_VERSION="27.1.0"
PLATFORM="x86_64-unknown-linux-gnu"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Stellar CLI Setup (v${STELLAR_VERSION})                              ║"
echo "║  https://developers.stellar.org/docs/build/smart-contracts/  ║"
echo "║  getting-started/setup                                        ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# ── Step 1: Rust toolchain ──────────────────────────────────────────
echo "▶ Step 1: Rust toolchain"
if command -v rustc &>/dev/null; then
  echo "  ✓ rustc already installed: $(rustc --version)"
else
  echo "  → Installing rustup + stable toolchain..."
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
  echo "  ✓ Installed: $(source "$HOME/.cargo/env" && rustc --version)"
fi
source "$HOME/.cargo/env" 2>/dev/null || true
echo ""

# ── Step 2: wasm32v1-none target ────────────────────────────────────
echo "▶ Step 2: wasm32v1-none target (required for Soroban contracts)"
if rustup target list --installed 2>/dev/null | grep -q "wasm32v1-none"; then
  echo "  ✓ wasm32v1-none target already installed"
else
  echo "  → Adding wasm32v1-none target..."
  rustup target add wasm32v1-none
  echo "  ✓ Installed"
fi
echo ""

# ── Step 3: rust-analyzer (for IDE LSP autocomplete) ────────────────
echo "▶ Step 3: rust-analyzer (LSP server for IDE autocomplete)"
if rustup component list --installed 2>/dev/null | grep -q "rust-analyzer"; then
  echo "  ✓ rust-analyzer already installed: $(rust-analyzer --version 2>&1 | head -1)"
else
  echo "  → Installing rust-analyzer component..."
  rustup component add rust-analyzer
  echo "  ✓ Installed: $(rust-analyzer --version 2>&1 | head -1)"
fi
echo ""

# ── Step 4: stellar-cli ─────────────────────────────────────────────
echo "▶ Step 4: stellar-cli v${STELLAR_VERSION}"
if command -v stellar &>/dev/null && stellar --version 2>&1 | grep -q "$STELLAR_VERSION"; then
  echo "  ✓ stellar-cli $STELLAR_VERSION already installed"
else
  echo "  → Downloading pre-built binary from GitHub releases..."
  URL="https://github.com/stellar/stellar-cli/releases/download/v${STELLAR_VERSION}/stellar-cli-${STELLAR_VERSION}-${PLATFORM}.tar.gz"
  curl -fsSL -o /tmp/stellar-cli.tar.gz "$URL"
  tar -xzf /tmp/stellar-cli.tar.gz -C /tmp/
  mkdir -p "$HOME/.cargo/bin"
  cp /tmp/stellar "$HOME/.cargo/bin/stellar"
  chmod +x "$HOME/.cargo/bin/stellar"
  rm -f /tmp/stellar-cli.tar.gz /tmp/stellar
  echo "  ✓ Installed: $(stellar --version 2>&1 | head -1)"
fi
echo ""

# ── Step 5: Shell completion ────────────────────────────────────────
echo "▶ Step 5: Shell autocompletion (bash + zsh + fish)"
echo "  → Generating completion scripts via 'stellar completion --shell <shell>'..."

# Bash
mkdir -p "$HOME/.bash_completion.d"
stellar completion --shell bash > "$HOME/.bash_completion.d/stellar" 2>/dev/null
echo "  ✓ bash completion: $(wc -l < "$HOME/.bash_completion.d/stellar") lines"

# Zsh
mkdir -p "$HOME/.zsh/completion"
stellar completion --shell zsh > "$HOME/.zsh/completion/_stellar" 2>/dev/null
echo "  ✓ zsh completion: $(wc -l < "$HOME/.zsh/completion/_stellar") lines"

# Fish
mkdir -p "$HOME/.config/fish/completions"
stellar completion --shell fish > "$HOME/.config/fish/completions/stellar.fish" 2>/dev/null
echo "  ✓ fish completion: $(wc -l < "$HOME/.config/fish/completions/stellar.fish") lines"
echo ""

# ── Step 6: ~/.bashrc configuration ─────────────────────────────────
echo "▶ Step 6: Configure ~/.bashrc"

# Check if already configured (avoid duplicate entries)
if [ -f "$HOME/.bashrc" ] && grep -q "bash_completion.d/stellar" "$HOME/.bashrc"; then
  echo "  ✓ ~/.bashrc already configured for stellar completion"
else
  cat >> "$HOME/.bashrc" << 'BASHRC_CONFIG'

# ── Stellar CLI ──────────────────────────────────────────────────────
# Shell autocompletion (generated by: stellar completion --shell bash)
if [ -f "$HOME/.bash_completion.d/stellar" ]; then
    source "$HOME/.bash_completion.d/stellar"
fi

# Cargo / Rust bin (stellar-cli is installed here)
export PATH="$HOME/.cargo/bin:$PATH"
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$HOME/.rustup"

# Local bin
export PATH="$HOME/.local/bin:$PATH"

# Aliases for common stellar commands
alias sc="stellar contract"
alias sb="stellar contract build"
alias sd="stellar contract deploy"
alias si="stellar contract inspect"
alias sf="stellar contract fetch"
# ── End Stellar CLI ──────────────────────────────────────────────────
BASHRC_CONFIG
  echo "  ✓ Added stellar completion + PATH + aliases to ~/.bashrc"
fi
echo ""

# ── Summary ──────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ✓ Setup complete!                                           ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║                                                              ║"
echo "║  Installed:                                                  ║"
echo "║    • rustc $(rustc --version 2>&1 | sed 's/rustc //')                          ║"
echo "║    • cargo $(cargo --version 2>&1 | sed 's/cargo //')                          ║"
echo "║    • rust-analyzer $(rust-analyzer --version 2>&1 | head -1 | sed 's/rust-analyzer //')          ║"
echo "║    • stellar-cli $(stellar --version 2>&1 | head -1 | sed 's/stellar //')                  ║"
echo "║    • wasm32v1-none target                                    ║"
echo "║                                                              ║"
echo "║  Shell completion installed for: bash, zsh, fish             ║"
echo "║                                                              ║"
echo "║  Next steps:                                                 ║"
echo "║    1. Restart your shell OR run: source ~/.bashrc            ║"
echo "║    2. Try autocomplete: stellar <TAB>                        ║"
echo "║       → stellar contract <TAB>                               ║"
echo "║       → stellar contract build --<TAB>                       ║"
echo "║                                                              ║"
echo "║  Aliases added:                                              ║"
echo "║    sc  = stellar contract                                    ║"
echo "║    sb  = stellar contract build                              ║"
echo "║    sd  = stellar contract deploy                             ║"
echo "║    si  = stellar contract inspect                            ║"
echo "║    sf  = stellar contract fetch                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
