import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

/**
 * GET /api/autocomplete/rustdoc-index
 *
 * Returns symbol indexes for autocomplete.
 *
 * Query params:
 *   (none)        — return soroban-sdk index (always available)
 *   ?deps=true    — return soroban-sdk + all cached dep indexes (merged)
 *
 * Dep indexes are generated by POST /api/autocomplete/build-deps (called
 * after a build completes). Each dep is cached per package@version.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Index directory — check /tmp first (where build-deps writes new indexes),
// then fall back to data/ (where pre-built indexes are committed).
// This way the committed soroban-sdk-index.json is always found, and
// dynamically-built dep indexes are found in /tmp without triggering
// Next.js file-watcher reloads.
const TMP_INDEX_DIR = path.join("/tmp", "soroban-rustdoc-index");
const DATA_INDEX_DIR = path.join(process.cwd(), "data", "rustdoc-index");

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const includeDeps = url.searchParams.get("deps") === "true";

    // soroban-sdk index lives in data/ (committed pre-built index)
    const sdkPath = path.join(DATA_INDEX_DIR, "soroban-sdk-index.json");

    // Load soroban-sdk index (always)
    let sdkIndex: { crate: string; version: string; symbols: unknown[]; total_count: number } | null = null;
    try {
      sdkIndex = JSON.parse(await fs.readFile(/*turbopackIgnore: true*/ sdkPath, "utf-8"));
    } catch {
      return NextResponse.json(
        { error: "soroban-sdk index not built. Run scripts/build-soroban-rustdoc.sh" },
        { status: 503 }
      );
    }

    if (!sdkIndex) {
      return NextResponse.json({ error: "Failed to parse sdk index" }, { status: 500 });
    }

    if (!includeDeps) {
      return NextResponse.json(sdkIndex);
    }

    // Load all cached dep indexes — check /tmp first, then data/
    // /tmp is where build-deps writes new indexes (outside the project dir
    // so it doesn't trigger file-watcher reloads). data/ has any pre-built
    // committed indexes.
    const depIndexes: Array<{ crate: string; version: string; symbols: unknown[]; total_count: number }> = [];
    const seenFiles = new Set<string>();

    for (const dir of [TMP_INDEX_DIR, DATA_INDEX_DIR]) {
      let files: string[] = [];
      try {
        files = await fs.readdir(/*turbopackIgnore: true*/ dir);
      } catch {
        continue; // dir doesn't exist yet
      }
      for (const file of files) {
        if (seenFiles.has(file)) continue; // don't load the same file twice
        if (!file.endsWith(".json")) continue;
        if (file === "soroban-sdk-index.json" || file === "std-index.json" || file.startsWith("std-")) continue;
        try {
          const data = JSON.parse(await fs.readFile(/*turbopackIgnore: true*/ path.join(dir, file), "utf-8"));
          depIndexes.push(data);
          seenFiles.add(file);
        } catch {}
      }
    }

    // Merge all symbols
    const sdk = sdkIndex; // non-null alias for TS
    const allSymbols = [
      ...(sdk.symbols || []),
      ...depIndexes.flatMap((d) => d.symbols || []),
    ];

    return NextResponse.json({
      crate: "merged",
      version: "dynamic",
      symbols: allSymbols,
      total_count: allSymbols.length,
      crates: [
        { name: sdk.crate, version: sdk.version, count: sdk.total_count },
        ...depIndexes.map((d) => ({ name: d.crate, version: d.version, count: d.total_count })),
      ],
    });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to load rustdoc index", detail: String(err) },
      { status: 500 }
    );
  }
}
