import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

/**
 * GET /api/autocomplete/rustdoc-index
 *
 * Returns symbol indexes for autocomplete.
 *
 * Query params:
 *   (none)        — return soroban-sdk index (always available)
 *   ?deps=true    — return soroban-sdk + all cached dep indexes (merged)
 *
 * Dep indexes are generated by POST /api/autocomplete/build-deps (called
 * after a build completes). Each dep is cached per package@version.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const INDEX_DIR = path.join(process.cwd(), "data", "rustdoc-index");

export async function GET(req: Request) {
  try {
    const url = new URL(req.url);
    const includeDeps = url.searchParams.get("deps") === "true";

    const sdkPath = path.join(INDEX_DIR, "soroban-sdk-index.json");

    // Load soroban-sdk index (always)
    let sdkIndex: { crate: string; version: string; symbols: unknown[]; total_count: number } | null = null;
    try {
      sdkIndex = JSON.parse(await fs.readFile(sdkPath, "utf-8"));
    } catch {
      return NextResponse.json(
        { error: "soroban-sdk index not built. Run scripts/build-soroban-rustdoc.sh" },
        { status: 503 }
      );
    }

    if (!sdkIndex) {
      return NextResponse.json({ error: "Failed to parse sdk index" }, { status: 500 });
    }

    if (!includeDeps) {
      return NextResponse.json(sdkIndex);
    }

    // Load all cached dep indexes
    const allFiles = await fs.readdir(INDEX_DIR);
    const depFiles = allFiles.filter(
      (f) => f.endsWith(".json") &&
        f !== "soroban-sdk-index.json" &&
        f !== "std-index.json" &&
        !f.startsWith("std-")
    );

    const depIndexes: Array<{ crate: string; version: string; symbols: unknown[]; total_count: number }> = [];
    for (const file of depFiles) {
      try {
        const data = JSON.parse(await fs.readFile(path.join(INDEX_DIR, file), "utf-8"));
        depIndexes.push(data);
      } catch {}
    }

    // Merge all symbols
    const sdk = sdkIndex; // non-null alias for TS
    const allSymbols = [
      ...(sdk.symbols || []),
      ...depIndexes.flatMap((d) => d.symbols || []),
    ];

    return NextResponse.json({
      crate: "merged",
      version: "dynamic",
      symbols: allSymbols,
      total_count: allSymbols.length,
      crates: [
        { name: sdk.crate, version: sdk.version, count: sdk.total_count },
        ...depIndexes.map((d) => ({ name: d.crate, version: d.version, count: d.total_count })),
      ],
    });
  } catch (err) {
    return NextResponse.json(
      { error: "Failed to load rustdoc index", detail: String(err) },
      { status: 500 }
    );
  }
}
